name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: SSH Deploy
        run: |
          echo ${{ secrets.SSH_USERNAME }}
          ssh root@${{ secrets.SSH_HOST }} << 'EOF'
            cd /root/spasskaya_bot
            git reset --hard HEAD
            git clean -fd
            git pull origin main

            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            docker-compose down
            docker-compose up -d --build
          EOF